/**
 * Example flow: preparing a YONAW vote with a Semaphore nullifier.
 */

import {
  buildYonawExternalNullifier,
  computeNullifierHash,
  generateYonawProof,
  buildMerkleProofPlaceholder,
} from './index';

async function example() {
  // Simulated identity (in real life generated by @semaphore-protocol/identity)
  const identity = {
    secret: 12345678901234567890n,
    commitment: 98765432109876543210n,
  };

  const favorId = 'favor-2026-08-07-001';
  const externalNullifier = buildYonawExternalNullifier(favorId);

  // Simulated Merkle proof (in real life from the group tree)
  const merkleProof = buildMerkleProofPlaceholder(
    identity.commitment,
    111222333444555666n, // current root
    [1n, 2n, 3n],
    [0, 1, 0]
  );

  // Signal = hash of the actual vote payload (Yes/No + tiers + why, etc.)
  const signal = 555666777888999000n;

  const fullProof = await generateYonawProof({
    identity,
    merkleProof,
    externalNullifier,
    signal,
  });

  console.log('External nullifier:', externalNullifier.toString());
  console.log('Nullifier hash:', fullProof.publicSignals.nullifierHash.toString());
  console.log('Merkle root:', fullProof.publicSignals.merkleRoot.toString());
  console.log('Proof ready for submission');
}

example().catch(console.error);
